### PR TITLE
Stored user theme choice using local storage

### PR DESCRIPTION
**Pull request by umairayub79**

### CODE REVIEW

**Comment by gouri-panda** [comment]
@umairayub79 #22 was assigned to @mendoc . You can raise a new issue and start solving it now.

**Comment by umairayub79** [comment]
it was not actually assigned 🤷‍♂️

**Comment by gouri-panda** [comment]
> it was not actually assigned 🤷‍♂️

It was actually my mistake. I said it on the comment.

**Comment by umairayub79** [comment]
can you at least lable it hacktoberfest-approved?

**Comment by gouri-panda** [comment]
@umairayub79 I can approve this but I can't merge it. is that ok?

**Comment by umairayub79** [comment]
@gouri-panda yeah I'm fine with that

**Review by gouri-panda — APPROVED** [review]

**Comment by umairayub79** [comment]
but make sure you label it _hacktoberfest-accepted_

**Comment by gouri-panda** [comment]
@umairayub79 hacktoberfest accept the pr if it has merged

**Comment by umairayub79** [comment]
@gouri-panda that's what they said in their blog : "_PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)_"

**Pull request closed without merging**
