### PR TITLE
Add support for more than 2 players

### PR DESCRIPTION
**Pull request by i-ze**
Player number can be controlled with 'players' query param. (Still limited to 2-6 players)

### CODE REVIEW

**Comment by NicholasACTran** [comment]
Can you look to resolve conflicts and take into account the ability to roll two dice?

**Comment by i-ze** [comment]
> Can you look to resolve conflicts and take into account the ability to roll two dice?

Updated. Technically it's possible to have more than 4 players, but for that additional changes required for the UI.

**Comment by NicholasACTran** [comment]
There's a bug fix that just got merged in that changes some logic around ending games. Please check here: https://github.com/gouri-panda/Pig-game/pull/74 and then just incorporate that logic in the newGame() and checkWinner() methods.

**Comment by zoltanszopory-tw** [comment]
Updated

**Comment by NicholasACTran** [comment]
This looks good, except, is there any way to add players via UI, or is the only way programmatically?

**Comment by zoltanszopory-tw** [comment]
> This looks good, except, is there any way to add players via UI, or is the only way programmatically?

Currently it's only possible with ?players=NUM query parameters, but AFAIK someone else is already working on the input modal.

**Comment by i-ze** [comment]
> This looks good, except, is there any way to add players via UI, or is the only way programmatically?

Currently it's only possible with ?players=NUM query parameter, but AFAIK someone else is already working on the input modal.

**Pull request merged**
