### PR TITLE
Add contribution.md

### PR DESCRIPTION
**Pull request by Frankie-B**
Created a contribution.md file and a proposed format for submission and the first entry. This is my first attempt at contributing to open source. I hope it helps.

### CODE REVIEW

**Comment by gouri-panda** [comment]
@Frankie-B contribution.md file is already created. Thanks for the  PR.

**Comment by gouri-panda** [comment]
you can add the contributor's list in the contribution.md file.

**Comment by Frankie-B** [comment]
Happy to. Do you have a list already? I am very new to OSS 🙈

**Comment by gouri-panda** [comment]
@Frankie-B sure  look #27 you can find it.

**Comment by Frankie-B** [comment]
Okay on it.

**Pull request closed without merging**
