### PR TITLE
feat: Show game rules in a modal

### LINKED ISSUE #52: Show rules for news players
It will be useful to have an button that shows rules for new players.

I want to work on.

### PR DESCRIPTION
**Pull request by mendoc**
Fixes #52 

From now on, it is possible to read the rules of the game.

I added a button that displays the rules of the game in a modal.
The dark theme is also considered.

### CODE REVIEW

**Comment by gouri-panda** [comment]
@mendoc I changed the description. It is the ideal way to automatic close a issue by following PR.

**Comment by mendoc** [comment]
Should I do something here or are you checking the work?

**Comment by gouri-panda** [comment]
> Should I do something here or are you checking the work?

@mendoc i am reviewing it now. Don't worry about it.

**Comment by mendoc** [comment]
@gouri-panda I have resolved conflicts. It's ready for merging.

**Comment by gouri-panda** [comment]
@mendoc great work!

**Pull request merged**
