### PR TITLE
Solved some Issues

### PR DESCRIPTION
**Pull request by ghost**
## Solved the Below
* Goal number doesn't show if we added 4 digits and more #65
* Players should choose their name #63
* Add documentation in all the javascript method and file #41 

* Also removed some Bug
* Changed the view of the Theme changer and added a Tooltip to it.

Screenshot 2020-10-08 072003
Screenshot 2020-10-08 072130
Screenshot 2020-10-08 071856
Screenshot 2020-10-08 071935

### CODE REVIEW

**Review by gouri-panda — CHANGES_REQUESTED** [review]
@azax25547 Please don't change the style of the player.It should intact with this PR request.

**Comment by azax25547** [comment]
> @azax25547 Please don't change the style of the player.It should intact with this PR request.

I just updated player names font. Anything change if you want then say, i will commit em

**Comment by gouri-panda** [comment]
@azax25547 Also Please don't replace the dark theme switch. it should be the upper right corner. Revert the change.

**Comment by azax25547** [comment]
> @azax25547 Also Please don't replace the dark theme switch. it should be the upper right corner. Revert the change.

Hi All the UI changes i have made are reverted back. Thanks

**Comment by NicholasACTran** [comment]
@azax25547 Can you fix merge conflicts then test again to double check functionality?

**Comment by NicholasACTran** [comment]
Closes #65 
Closes #63

**Pull request closed without merging**
